[BED-294] More descriptive error message when macros values are missing
redsift/spf pull request #18
Opened 2023-07-21 09:17 UTC by csucu

Error message now returns which macros are missing

2023-07-21 09:55 UTC, jpicht submitted a review, later dismissed

2023-07-28 12:08 UTC, dmotylev requested changes
We can not add any functionality to the lib without tests.

2023-07-31 14:06 UTC, illyasch approved these changes

2023-07-31 15:08 UTC, csucu commented
> We can not add any functionality to the lib without tests.

Tests have now been added

2023-07-31 15:13 UTC, dmotylev approved these changes

2023-07-31 15:18 UTC, merged